Repository thelia/thelia, pull requests merged in 2018-03, with the labels that each got.

#2483 Fix color status in search order
  templates/backOffice/default/search.html
Labels: Version 2.3.5, Version 2.4.0, missing

#2482 FreeOrder: round total amount to avoid problems with floats
  local/modules/FreeOrder/FreeOrder.php
Labels: Version 2.3.5, Version 2.4.0, bug

#2481 Fix bug code promo
  core/lib/Thelia/Form/CouponCode.php
Labels: Version 2.3.5, Version 2.4.0, bug

#2479 disallow cart path but not words starting with cart
  web/robots.txt
Labels: Version 2.3.5, Version 2.4.0, bug

#2492 Removed useless notice log
  core/lib/Thelia/Core/Template/Loop/Accessory.php
Labels: Version 2.4.0
