Repository thelia/thelia, pull requests merged in 2018-11, with the labels that each got.

#2557 BO UI Add possibility to remove btn text
  templates/backOffice/default/renderer/buttons.html
Labels: UI/UX, Version 2.4.0, enhancement

#2558 BO UI renderer btn create
  templates/backOffice/default/administrators.html
  templates/backOffice/default/api.html
  templates/backOffice/default/attribute-edit.html
  templates/backOffice/default/attributes.html
  templates/backOffice/default/brands.html
  templates/backOffice/default/categories.html
  templates/backOffice/default/countries.html
  templates/backOffice/default/coupon-list.html
  templates/backOffice/default/currencies.html
  templates/backOffice/default/customer-edit.html
  templates/backOffice/default/customers.html
  templates/backOffice/default/feature-edit.html
  templates/backOffice/default/features.html
  templates/backOffice/default/folders.html
  templates/backOffice/default/hooks.html
  templates/backOffice/default/includes/product-prices-tab.html
  templates/backOffice/default/languages.html
  templates/backOffice/default/messages.html
  templates/backOffice/default/module-hooks.html
  templates/backOffice/default/order-status.html
  templates/backOffice/default/profiles.html
  templates/backOffice/default/renderer/buttons.html
  templates/backOffice/default/shipping-configuration.html
  templates/backOffice/default/states.html
  templates/backOffice/default/taxes-rules.html
  templates/backOffice/default/templates.html
  templates/backOffice/default/variables.html
Labels: UI/UX, Version 2.4.0, enhancement

#2556 Update propel with event dispatcher
  composer.json
  composer.lock
  core/lib/Thelia/Core/Propel/Generator/Builder/Om/EventBuilder.php
  core/lib/Thelia/Core/PropelInitService.php
  core/lib/Thelia/Core/Thelia.php
Labels: Version 2.4.0, enhancement, work in progress

#2565 Change Thelia dev ip protection
  web/index.php
  web/index_dev.php
Labels: bug

#2560 Lang should be active and currency visible to be used in front office
  core/lib/Thelia/Core/EventListener/RequestListener.php
  core/lib/Thelia/Core/Security/User/UserInterface.php
  core/lib/Thelia/Model/Api.php
  core/lib/Thelia/Model/Customer.php
Labels: Version 2.4.0, bug

#2561 Order status management improvement
  core/lib/Thelia/Model/OrderProductQuery.php
  core/lib/Thelia/Model/OrderQuery.php
  core/lib/Thelia/Model/OrderStatusQuery.php
  local/modules/TheliaSmarty/Template/Plugins/DataAccessFunctions.php
Labels: Version 2.4.0, enhancement

#2568 Implementation symfony dotenv
  .env.dist
  composer.json
  composer.lock
  core/Thelia
  core/composer.json
  web/index.php
  web/index_dev.php
Labels: Version 2.4.0, enhancement

#2569 Prepare version 2.4.0-alpha2
  core/bootstrap.php
  local/modules/Carousel/Config/module.xml
  local/modules/Cheque/Config/module.xml
  local/modules/Colissimo/Config/module.xml
  local/modules/FreeOrder/Config/module.xml
  local/modules/Front/Config/module.xml
  local/modules/HookAdminHome/Config/module.xml
  local/modules/HookAnalytics/Config/module.xml
  local/modules/HookCart/Config/module.xml
  local/modules/HookContact/Config/module.xml
  local/modules/HookCurrency/Config/module.xml
  local/modules/HookCustomer/Config/module.xml
  local/modules/HookLang/Config/module.xml
  local/modules/HookLinks/Config/module.xml
  local/modules/HookNavigation/Config/module.xml
  local/modules/HookNewsletter/Config/module.xml
  local/modules/HookProductsNew/Config/module.xml
  local/modules/HookProductsOffer/Config/module.xml
  local/modules/HookSearch/Config/module.xml
  local/modules/HookSocial/Config/module.xml
  local/modules/TheliaMigrateCountry/Config/module.xml
  local/modules/TheliaSmarty/Config/module.xml
  local/modules/Tinymce/Config/module.xml
  local/modules/VirtualProductControl/Config/module.xml
  local/modules/VirtualProductDelivery/Config/module.xml
  tests/phpunit/Thelia/Tests/Module/Validator/ModuleValidatorTest.php
Labels: Version 2.4.0

#2570 Fix count null value php7.2
  core/lib/Thelia/Module/Validator/ModuleValidator.php
  templates/backOffice/default/currencies.html
  templates/backOffice/default/renderer/buttons.html
  templates/backOffice/default/variables.html
Labels: bug

#2571 Fix thelia migration 2.3.4 -> 2.4.0-alpha2
  setup/update/sql/2.3.4.sql
  setup/update/sql/2.4.0-alpha1.sql
  setup/update/tpl/2.3.4.sql.tpl
  setup/update/tpl/2.4.0-alpha1.sql.tpl
Labels: bug

#2573 BO UI Fix btn edit content
  templates/backOffice/default/folders.html
Labels: bug

#2574 A missing hook will throw an error in dev mode only
  local/modules/TheliaSmarty/Template/Plugins/Hook.php
Labels: Version 2.4.0

#2577 Set the error URL of the payment form
  templates/frontOffice/default/order-invoice.html
Labels: Version 2.4.0, bug

#2576 Add deprecated model event
  core/lib/Thelia/Core/Event/AccessoryEvent.php
  core/lib/Thelia/Core/Event/Address/AddressEvent.php
  core/lib/Thelia/Core/Event/Area/AreaEvent.php
  core/lib/Thelia/Core/Event/Attribute/AttributeAvEvent.php
  core/lib/Thelia/Core/Event/Attribute/AttributeEvent.php
  core/lib/Thelia/Core/Event/Brand/BrandEvent.php
  core/lib/Thelia/Core/Event/Category/CategoryAssociatedContentEvent.php
  core/lib/Thelia/Core/Event/Category/CategoryEvent.php
  core/lib/Thelia/Core/Event/Config/ConfigEvent.php
  core/lib/Thelia/Core/Event/Content/ContentEvent.php
  core/lib/Thelia/Core/Event/Country/CountryEvent.php
  core/lib/Thelia/Core/Event/Currency/CurrencyEvent.php
  core/lib/Thelia/Core/Event/Customer/CustomerEvent.php
  core/lib/Thelia/Core/Event/Feature/FeatureAvEvent.php
  core/lib/Thelia/Core/Event/Feature/FeatureEvent.php
  core/lib/Thelia/Core/Event/FeatureProduct/FeatureProductEvent.php
  core/lib/Thelia/Core/Event/Folder/FolderEvent.php
  core/lib/Thelia/Core/Event/Lang/LangEvent.php
  core/lib/Thelia/Core/Event/Message/MessageEvent.php
  core/lib/Thelia/Core/Event/Product/ProductAssociatedContentEvent.php
  core/lib/Thelia/Core/Event/Product/ProductEvent.php
  core/lib/Thelia/Core/Event/Sale/SaleEvent.php
  core/lib/Thelia/Core/Event/State/StateEvent.php
  core/lib/Thelia/Core/Event/Template/TemplateEvent.php
  core/lib/Thelia/Core/Event/TheliaEvents.php
  core/lib/Thelia/Model/Accessory.php
  core/lib/Thelia/Model/Api.php
  core/lib/Thelia/Model/Attribute.php
  core/lib/Thelia/Model/OrderFeature.php
  core/lib/Thelia/Model/OrderFeatureQuery.php
  core/lib/Thelia/Model/Tools/ModelEventDispatcherTrait.php
Labels: Version 2.4.0

#2579 Composer remove symfony/icu on thelia core
  core/composer.json
Labels: Version 2.4.0

#2580 Fix module postActivation with new propel integration
  core/lib/Thelia/Core/PropelInitService.php
  core/lib/Thelia/Module/BaseModule.php
  tests/phpunit/Thelia/Tests/ContainerAwareTestCase.php
Labels: Version 2.4.0, bug

#2582 Fix loop feature, filter template
  core/lib/Thelia/Core/Template/Loop/Feature.php
Labels: Version 2.4.0, bug

#2585 Improve propel cache
  core/bootstrap.php
  core/lib/Thelia/Config/Resources/config.xml
  core/lib/Thelia/Core/Bundle/TheliaBundle.php
  core/lib/Thelia/Core/EventListener/PropelListener.php
  core/lib/Thelia/Core/Propel/Generator/Builder/Om/Mixin/ImplementationClassTrait.php
  core/lib/Thelia/Core/PropelInitService.php
Labels: Version 2.4.0
