Repository thelia/thelia, pull requests merged in 2018-12, with the labels that each got.

#2586 Fix for #2505 BackOffice dashboard refresh button
  local/modules/HookAdminHome/Controller/HomeController.php
Labels: Version 2.4.0, bug

#2587 Add cache for loop ArgDefinitions
  core/lib/Thelia/Core/Template/Element/BaseLoop.php
Labels: Version 2.4.0

#2595 Fix Issue #2504
  templates/backOffice/default/I18n/fr_FR.php
Labels: Version 2.4.0

#2600 Check if symlink() is working when installing Thelia
  web/install/end.php
Labels: Version 2.4.0, enhancement
