Repository thelia/thelia, pull requests merged in 2018-10, with the labels that each got.

#2532 Add url sitemap.xml
  local/modules/Front/Config/front.xml
Labels: Version 2.4.0, enhancement

#2533 Fix an infinite loop when the cache is cleared
  core/lib/Thelia/Action/Cache.php
  core/lib/Thelia/Command/CacheClear.php
  core/lib/Thelia/Core/Event/Cache/CacheEvent.php
  core/lib/Thelia/Core/EventListener/PropelListener.php
  tests/phpunit/Thelia/Tests/Action/CacheTest.php
Labels: Version 2.4.0, bug

#2500 Fix newsletter unsubscribe/subscribe
  core/lib/Thelia/Action/Newsletter.php
  local/modules/Front/Controller/CustomerController.php
Labels: Version 2.4.0, bug

#2495 Prevent setting the only default PSE to non-default
  core/lib/Thelia/Action/ProductSaleElement.php
Labels: Version 2.4.0, bug

#2476 Un-comment of exception processing in the processUpdateAction()
  core/lib/Thelia/Controller/Admin/AbstractCrudController.php
Labels: Version 2.4.0, bug

#2493 Keep product price & information when deleting the last PSE of a product
  core/lib/Thelia/Action/ProductSaleElement.php
Labels: Version 2.4.0, enhancement

#2535 Fix not countable args
  core/lib/Thelia/Core/Template/Loop/Area.php
  core/lib/Thelia/Core/Template/Loop/CountryArea.php
Labels: Version 2.4.0, bug

#2537 test if the module exists on the file system before generation cache
  core/lib/Thelia/Core/Propel/Schema/SchemaLocator.php
Labels: Version 2.4.0, bug

#2469 New feature: template inheritance
  core/lib/Thelia/Action/Lang.php
  core/lib/Thelia/Action/Order.php
  core/lib/Thelia/Action/ProductSaleElement.php
  core/lib/Thelia/Controller/Admin/MessageController.php
  core/lib/Thelia/Controller/Admin/TranslationsController.php
  core/lib/Thelia/Core/Hook/HookHelper.php
  core/lib/Thelia/Core/Template/Assets/AssetResolverInterface.php
  core/lib/Thelia/Core/Template/Assets/AsseticAssetManager.php
  core/lib/Thelia/Core/Template/Exception/InvalidDescriptorException.php
  core/lib/Thelia/Core/Template/Exception/TemplateException.php
  core/lib/Thelia/Core/Template/Parser/ParserAssetResolverFallback.php
  core/lib/Thelia/Core/Template/ParserInterface.php
  core/lib/Thelia/Core/Template/TemplateDefinition.php
  core/lib/Thelia/Core/Template/Validator/TemplateDescriptor.php
  core/lib/Thelia/Core/Template/Validator/TemplateDescriptorValidator.php
  core/lib/Thelia/Core/Template/Validator/TemplateValidator.php
  core/lib/Thelia/Core/Template/Validator/schema/template/template-1_0.xsd
  core/lib/Thelia/Core/Thelia.php
  core/lib/Thelia/Model/Message.php
  local/modules/TheliaSmarty/Template/Assets/SmartyAssetsManager.php
  local/modules/TheliaSmarty/Template/Assets/SmartyAssetsResolver.php
  local/modules/TheliaSmarty/Template/Plugins/AdminUtilities.php
  local/modules/TheliaSmarty/Template/Plugins/Form.php
  local/modules/TheliaSmarty/Template/Plugins/Module.php
  local/modules/TheliaSmarty/Template/SmartyParser.php
  templates/backOffice/default/admin-layout.tpl
  templates/backOffice/default/template.xml
  templates/email/default/template.xml
  templates/frontOffice/default/template.xml
  templates/pdf/default/template.xml
  tests/phpunit/Thelia/Tests/Api/ProductSaleElementsControllerTest.php
Labels: Version 2.4.0, documentation update required, enhancement

#2541 add remove_zero_decimal parameter
  core/lib/Thelia/Tools/MoneyFormat.php
  local/modules/TheliaSmarty/Template/Plugins/Format.php
Labels: Version 2.4.0, enhancement

#2241 Last URL view for catalog
  core/lib/Thelia/Core/EventListener/RequestListener.php
  core/lib/Thelia/Core/HttpFoundation/Session/Session.php
  local/modules/TheliaSmarty/Template/Plugins/UrlGenerator.php
  templates/frontOffice/default/cart.html
Labels: Version 2.4.0, documentation update required, enhancement

#2542 Smarty upgrade to version 3.1.33
  composer.json
  composer.lock
  local/modules/TheliaSmarty/Template/AbstractSmartyPlugin.php
  local/modules/TheliaSmarty/Template/Plugins/TheliaLoop.php
  local/modules/TheliaSmarty/Template/SmartyParser.php
Labels: Version 2.4.0, enhancement

#2544 Fix constants propel deprecated
  core/lib/Thelia/Action/Order.php
  core/lib/Thelia/Action/Product.php
  core/lib/Thelia/Action/ProductSaleElement.php
  core/lib/Thelia/Command/ModuleListCommand.php
  core/lib/Thelia/Controller/Api/TaxRuleController.php
  core/lib/Thelia/Core/Template/Loop/Attribute.php
  core/lib/Thelia/Core/Template/Loop/AttributeAvailability.php
  core/lib/Thelia/Core/Template/Loop/AttributeCombination.php
  core/lib/Thelia/Core/Template/Loop/Content.php
  core/lib/Thelia/Core/Template/Loop/Coupon.php
  core/lib/Thelia/Core/Template/Loop/Customer.php
  core/lib/Thelia/Core/Template/Loop/Feature.php
  core/lib/Thelia/Core/Template/Loop/FeatureValue.php
  core/lib/Thelia/Core/Template/Loop/Order.php
  core/lib/Thelia/Core/Template/Loop/OrderProduct.php
  core/lib/Thelia/Core/Template/Loop/Product.php
  core/lib/Thelia/Core/Template/Loop/ProductSaleElements.php
  core/lib/Thelia/ImportExport/Export/Type/ContentExport.php
  core/lib/Thelia/ImportExport/Export/Type/CustomerExport.php
  core/lib/Thelia/ImportExport/Export/Type/OrderExport.php
  core/lib/Thelia/ImportExport/Export/Type/ProductPricesExport.php
  core/lib/Thelia/ImportExport/Export/Type/ProductSEOExport.php
  core/lib/Thelia/ImportExport/Export/Type/ProductTaxedPricesExport.php
  core/lib/Thelia/Model/Content.php
  core/lib/Thelia/Model/Order.php
  core/lib/Thelia/Model/Product.php
  core/lib/Thelia/Model/RewritingUrlQuery.php
  core/lib/Thelia/Model/TaxRuleQuery.php
  tests/phpunit/Thelia/Tests/Api/ProductSaleElementsControllerTest.php
  tests/phpunit/Thelia/Tests/Api/TaxRuleControllerTest.php
  tests/phpunit/Thelia/Tests/Form/FirewallTest.php
Labels: Version 2.4.0

#2546 Undefined loop should be in the loop stack
  local/modules/TheliaSmarty/Template/Plugins/TheliaLoop.php
Labels: Version 2.4.0, bug

#2551 Fix #2525 microdata
  templates/frontOffice/default/includes/single-product.html
  templates/frontOffice/default/misc/breadcrumb.tpl
  templates/frontOffice/default/product.html
Labels: Version 2.4.0, enhancement

#2545 Customer preferred language selection
  core/lib/Thelia/Action/Customer.php
  core/lib/Thelia/Config/I18n/en_US.php
  core/lib/Thelia/Config/I18n/fr_FR.php
  core/lib/Thelia/Config/Resources/action.xml
  core/lib/Thelia/Controller/Admin/CustomerController.php
  core/lib/Thelia/Form/CustomerCreateForm.php
  core/lib/Thelia/Form/CustomerUpdateForm.php
  core/lib/Thelia/Model/Customer.php
  local/modules/Front/Controller/CustomerController.php
  templates/backOffice/default/customer-edit.html
  templates/backOffice/default/customers.html
  templates/frontOffice/default/account-update.html
  templates/frontOffice/default/register.html
  tests/phpunit/Thelia/Tests/Action/CustomerTest.php
Labels: UI/UX, Version 2.4.0, enhancement, i18n

#2547 BO new buttons integration
  templates/backOffice/default/I18n/fr_FR.php
  templates/backOffice/default/administrators.html
  templates/backOffice/default/api.html
  templates/backOffice/default/assets/css/styles.css
  templates/backOffice/default/assets/less/thelia/buttons.less
  templates/backOffice/default/assets/less/thelia/tables.less
  templates/backOffice/default/attributes.html
  templates/backOffice/default/brands.html
  templates/backOffice/default/categories.html
  templates/backOffice/default/configuration.html
  templates/backOffice/default/countries.html
  templates/backOffice/default/coupon-list.html
  templates/backOffice/default/currencies.html
  templates/backOffice/default/customers.html
  templates/backOffice/default/export.html
  templates/backOffice/default/features.html
  templates/backOffice/default/folders.html
  templates/backOffice/default/hooks.html
  templates/backOffice/default/import.html
  templates/backOffice/default/includes/module-block.html
  templates/backOffice/default/includes/module-hook-block.html
  templates/backOffice/default/languages.html
  templates/backOffice/default/messages.html
  templates/backOffice/default/modules.html
  templates/backOffice/default/order-status.html
  templates/backOffice/default/orders.html
  templates/backOffice/default/profiles.html
  templates/backOffice/default/renderer/buttons.html
  templates/backOffice/default/sales.html
  templates/backOffice/default/search.html
  templates/backOffice/default/shipping-configuration.html
  templates/backOffice/default/shipping-zones.html
  templates/backOffice/default/states.html
  templates/backOffice/default/taxes-rules.html
  templates/backOffice/default/templates.html
  templates/backOffice/default/variables.html
Labels: UI/UX, Version 2.4.0, enhancement

#2552 Minor back-office UI improvements
  core/lib/Thelia/Controller/Admin/MailingSystemController.php
  core/lib/Thelia/Form/MailingSystemModificationForm.php
  templates/backOffice/default/I18n/fr_FR.php
  templates/backOffice/default/api.html
  templates/backOffice/default/assets/css/styles.css
  templates/backOffice/default/assets/less/thelia/thelia.less
  templates/backOffice/default/includes/catalog-breadcrumb.html
  templates/backOffice/default/includes/module-block.html
  templates/backOffice/default/mailing-system.html
  templates/backOffice/default/orders.html
  templates/backOffice/default/variables.html
Labels: UI/UX, Version 2.4.0, bug
