Repository thelia/thelia, pull requests merged in 2019-03, with the labels that each got.

#2650 Fix attribute-edit.html smarty error
  templates/backOffice/default/attribute-edit.html
Labels: Version 2.4.0, bug

#2648 Fix #2647 Wrong edition URL in message template
  templates/backOffice/default/messages.html
Labels: UI/UX, Version 2.4.0, bug

#2651 Allow to load tax rule without country
  core/lib/Thelia/Model/TaxRuleQuery.php
  core/lib/Thelia/TaxEngine/Calculator.php
Labels: Version 2.4.0, enhancement

#2655 Update var name error MailerFactory.php
  core/lib/Thelia/Mailer/MailerFactory.php
Labels: Version 2.4.0, bug

#2657 Add option to show/Hide stats bloc
  local/modules/HookAdminHome/Config/config.xml
  local/modules/HookAdminHome/Config/module.xml
  local/modules/HookAdminHome/Config/routing.xml
  local/modules/HookAdminHome/Controller/ConfigurationController.php
  local/modules/HookAdminHome/Controller/HomeController.php
  local/modules/HookAdminHome/Form/Configuration.php
  local/modules/HookAdminHome/Hook/AdminHook.php
  local/modules/HookAdminHome/Hook/HookAdminManager.php
  local/modules/HookAdminHome/HookAdminHome.php
  local/modules/HookAdminHome/templates/backOffice/default/admin-home-config.html
  local/modules/HookAdminHome/templates/backOffice/default/hook-admin-home-config.html
Labels: enhancement
