Repository thelia/thelia, pull requests merged in 2019-04, with the labels that each got.

#2661 Fix issue #2660
  templates/frontOffice/default/address-update.html
Labels: Version 2.4.0, bug

#2665 Fix bad translation key
  templates/backOffice/default/messages.html
Labels: Version 2.4.0, bug

#2664 Add BO brand search
  templates/backOffice/default/search.html
Labels: Version 2.4.0, enhancement

#2668 Dump version 2.3.5
  CHANGELOG.md
  Readme.md
  core/lib/Thelia/Core/Thelia.php
  core/lib/Thelia/Form/CouponCode.php
  local/modules/Carousel/Config/module.xml
  local/modules/Cheque/Config/module.xml
  local/modules/Colissimo/Config/module.xml
  local/modules/FreeOrder/Config/module.xml
  local/modules/FreeOrder/FreeOrder.php
  local/modules/HookAdminHome/Config/module.xml
  local/modules/HookAnalytics/Config/module.xml
  local/modules/HookCart/Config/module.xml
  local/modules/HookContact/Config/module.xml
  local/modules/HookCurrency/Config/module.xml
  local/modules/HookCustomer/Config/module.xml
  local/modules/HookLang/Config/module.xml
  local/modules/HookLinks/Config/module.xml
  local/modules/HookNavigation/Config/module.xml
  local/modules/HookNewsletter/Config/module.xml
  local/modules/HookProductsNew/Config/module.xml
  local/modules/HookProductsOffer/Config/module.xml
  local/modules/HookSearch/Config/module.xml
  local/modules/HookSocial/Config/module.xml
  local/modules/TheliaMigrateCountry/Config/module.xml
  local/modules/TheliaSmarty/Config/module.xml
  local/modules/Tinymce/Config/module.xml
  local/modules/VirtualProductControl/Config/module.xml
  local/modules/VirtualProductDelivery/Config/module.xml
  setup/insert.sql
  setup/update/sql/2.3.5.sql
  setup/update/tpl/2.3.5.sql.tpl
  templates/backOffice/default/forms/standard/form-field-attributes-renderer.html
  templates/backOffice/default/search.html
  web/robots.txt
Labels: Version 2.3.5
