Repository thelia/thelia, pull requests merged in 2019-01, with the labels that each got.

#2603 Added tax rule ID parameters to product loop
  core/lib/Thelia/Core/Template/Loop/Product.php
Labels: Version 2.4.0, documentation update required, enhancement

#2606 Added 3 new outputs to order loop
  core/lib/Thelia/Core/Template/Loop/Order.php
Labels: Version 2.4.0, documentation update required, enhancement

#2608 Fix required fields for form smtp configuration
  core/lib/Thelia/Form/MailingSystemModificationForm.php
Labels: Version 2.4.0, bug

#2610 MailerFactory::send() is now wrapped in an exception handler
  core/lib/Thelia/Mailer/MailerFactory.php
Labels: Version 2.4.0, bug, enhancement

#2613 Pagination fix
  templates/frontOffice/default/brand.html
  templates/frontOffice/default/category.html
  templates/frontOffice/default/includes/toolbar.html
Labels: UI/UX, Version 2.4.0, bug, enhancement

#2617 Added missing argument 'code' to the Coupon loop
  core/lib/Thelia/Core/Template/Loop/Coupon.php
Labels: Version 2.4.0

#2618 Fix smarty cache default value, add country and customer_discount
  local/modules/TheliaSmarty/Config/config.xml
  local/modules/TheliaSmarty/Template/Plugins/Cache.php
Labels: Version 2.4.0, documentation update required, missing

#2616 Allow use of CDN (e.g. alternate URL) on assets and documents
  core/lib/Thelia/Action/BaseCachedFile.php
  core/lib/Thelia/Action/Document.php
  core/lib/Thelia/Action/Image.php
  core/lib/Thelia/Tools/URL.php
  local/modules/TheliaSmarty/Template/Assets/SmartyAssetsResolver.php
  local/modules/TheliaSmarty/Template/Plugins/UrlGenerator.php
  setup/insert.sql.tpl
  tests/phpunit/Thelia/Tests/Tools/URLTest.php
  web/.htaccess
Labels: Version 2.4.0, documentation update required, enhancement

#2611 Fixed loop arguments cache initialisation
  core/lib/Thelia/Core/Template/Element/BaseLoop.php
Labels: Version 2.4.0, bug
