Repository thelia/thelia, pull requests merged in 2019-02, with the labels that each got.

#2628 Fix bo search order status color
  templates/backOffice/default/search.html
Labels: UI/UX, Version 2.4.0

#2625 Disabled output compression when generating site map
  local/modules/Front/Controller/SitemapController.php
Labels: Version 2.4.0, bug

#2623 Fix Tax calculator on country with state
  core/lib/Thelia/Model/TaxRuleQuery.php
Labels: Version 2.4.0, bug

#2621 Addd sort options to PSE loop, and allow to return all PSE
  core/lib/Thelia/Core/Template/Loop/ProductSaleElements.php
Labels: Version 2.4.0, documentation update required, enhancement

#2615 feature_values filter is now working in Product loop
  core/lib/Thelia/Core/Template/Loop/Product.php
  core/lib/Thelia/Type/IntToCombinedStringsListType.php
  tests/phpunit/Thelia/Tests/Type/IntToCombinedStringsListTypeTest.php
Labels: Version 2.4.0, bug, documentation update required, enhancement

#2609 Order details improvements
  templates/backOffice/default/I18n/en_US.php
  templates/backOffice/default/I18n/fr_FR.php
  templates/backOffice/default/assets/css/styles.css
  templates/backOffice/default/assets/less/thelia/tables.less
  templates/backOffice/default/assets/less/thelia/thelia.less
  templates/backOffice/default/attribute-edit.html
  templates/backOffice/default/feature-edit.html
  templates/backOffice/default/order-edit.html
  templates/backOffice/default/renderer/buttons.html
Labels: UI/UX, Version 2.4.0, enhancement

#2614 Shipping zone configuration improvement
  templates/backOffice/default/I18n/en_US.php
  templates/backOffice/default/I18n/fr_FR.php
  templates/backOffice/default/shipping-configuration-edit.html
Labels: UI/UX, Version 2.4.0, enhancement

#2607 Fix postage update when cart or coupon changes
  local/modules/Front/Controller/CartController.php
  local/modules/Front/Controller/CouponController.php
Labels: Version 2.4.0, bug

#2605 Fix wrong order total (issue #2604)
  core/lib/Thelia/Model/Order.php
  core/lib/Thelia/Model/OrderQuery.php
  local/modules/TheliaSmarty/Template/Plugins/DataAccessFunctions.php
Labels: Version 2.4.0, bug

#2629 Improve invoice and delivery interface
  templates/backOffice/default/I18n/fr_FR.php
  templates/backOffice/default/order-edit.html
  templates/backOffice/default/renderer/buttons.html
Labels: UI/UX, Version 2.4.0

#2634 Add phone on create customer modal
  templates/backOffice/default/customers.html
Labels: Version 2.4.0, enhancement

#2637 New "visible" parameter to pse loop
  core/lib/Thelia/Core/Template/Loop/ProductSaleElements.php
Labels: Version 2.4.0, documentation update done, documentation update required, enhancement

#2638 Remove Tlog in Propel init
  core/lib/Thelia/Core/PropelInitService.php
Labels: Version 2.4.0, bug

#2640 Update address-update.html
  templates/frontOffice/default/address-update.html
Labels: Version 2.4.0, bug

#2642 Fix missing parent preSave and postSave in Models
  core/lib/Thelia/Model/Content.php
  core/lib/Thelia/Model/Lang.php
  core/lib/Thelia/Model/Module.php
  core/lib/Thelia/Model/Product.php
  core/lib/Thelia/Model/Tools/I18nTimestampableTrait.php
Labels: Version 2.4.0, missing

#2644 Change two redirection from 302 to 301
  core/lib/Thelia/Core/Routing/RewritingRouter.php
  core/lib/Thelia/Core/Stack/ParamInitMiddleware.php
Labels: Version 2.4.0, enhancement

#2645 Add new event on contact submit
  core/lib/Thelia/Core/Event/Contact/ContactEvent.php
  core/lib/Thelia/Core/Event/TheliaEvents.php
  local/modules/Front/Controller/ContactController.php
Labels: Version 2.4.0, enhancement

#2646 Fix #2592 Add Delivery address in order loop search in
  core/lib/Thelia/Core/Template/Loop/Order.php
Labels: Version 2.4.0, enhancement
