Repository thelia/thelia, pull requests merged in 2020-03, with the labels that each got.

#2687 Added a findAllChildId() method
  core/lib/Thelia/Model/CategoryQuery.php
Labels: Version 2.4.0, enhancement

#2733 Carousel module improvements
  local/modules/Carousel/Carousel.php
  local/modules/Carousel/Config/schema.xml
  local/modules/Carousel/Config/thelia.sql
  local/modules/Carousel/Config/update/2.4.0.sql
  local/modules/Carousel/Controller/ConfigurationController.php
  local/modules/Carousel/Form/CarouselUpdateForm.php
  local/modules/Carousel/I18n/backOffice/default/en_US.php
  local/modules/Carousel/I18n/backOffice/default/fr_FR.php
  local/modules/Carousel/I18n/en_US.php
  local/modules/Carousel/I18n/fr_FR.php
  local/modules/Carousel/Loop/CarouselLoop.php
  local/modules/Carousel/Readme.md
  local/modules/Carousel/templates/backOffice/default/module_configuration.html
Labels: OK to MERGE, Version 2.4.0, enhancement

#2716 New reference related parameters to order loop
  core/lib/Thelia/Core/Template/Loop/Order.php
Labels: OK to MERGE, Version 2.4.0, documentation update required, enhancement

#2707 Improve product edit
  core/lib/Thelia/Config/Resources/routing/admin.xml
  core/lib/Thelia/Controller/Admin/ProductController.php
  templates/backOffice/default/ajax/product-related-tab.html
  templates/backOffice/default/product-edit.html
Labels: OK to MERGE, Version 2.4.0

#2685 Added arrow navigation to documents and images management
  core/lib/Thelia/Core/Template/Loop/Document.php
  core/lib/Thelia/Core/Template/Loop/Image.php
  templates/backOffice/default/document-edit.html
  templates/backOffice/default/image-edit.html
Labels: OK to MERGE, Version 2.4.0, documentation update required, enhancement

#2659 Improved ajax management in CartController
  local/modules/Front/Controller/CartController.php
Labels: OK to MERGE, Version 2.4.0, documentation update required, enhancement

#2584 Fix for getting choices options in forms
  local/modules/TheliaSmarty/Template/Plugins/Form.php
Labels: OK to MERGE, Version 2.4.0, enhancement

#2521 Add a new export "product I18n"
  core/lib/Thelia/Config/Resources/export.xml
  core/lib/Thelia/ImportExport/Export/Type/ProductI18nExport.php
Labels: OK to MERGE, Version 2.4.0, enhancement
